### ISSUE TITLE
EOF errors on Beiboot cluster

### ISSUE THREAD

**Issue by tschale** [Getdeck/beiboot#74]
Currently I'm working mainly with the 1.4.0-beta version, where I'm seeing regular EOF errors when working in a Beiboot cluster. They can happen quite frequently when using for example kubectl, but it can also happen that they rarely or never appear.

We should work on identifying a solution for that.

**Comment by tschale** [comment]
Maybe it's due to the ghostunnel pod, possibly it needs more resources.

**Comment by tschale** [comment]
> Maybe it's due to the ghostunnel pod, possibly it needs more resources.

I have increased the resources, but it didn't seem to have an effect...

**Comment by SteinRobert** [comment]
I did some investigation on this.
Problem is the service that is created to talk the the virtual cluster's api server. It points to all pod (server, agent-0, agent-1...). Of course the agents don't listen to 6443 - that's why sometimes you get an answer from the server, sometimes you get no answer because the request is directed to the client.

**Comment by tschale** [comment]
Nice finding! Did you get a chance to try it out yet?

**Comment by SteinRobert** [comment]
Yep works after the fix.
